### ISSUE TITLE
Error McBoaty not found McBoaty TilePrompter_v4, Upscaler_v4, Refiner_v4

### ISSUE THREAD

**Issue by romxluv** [MaraScott/ComfyUI_MaraScott_Nodes#126]
When loading the graph, the following node types were not found:
McBoaty_TilePrompter_v4
McBoaty_Upscaler_v4
McBoaty_Refiner_v4

Did I get the wrong version? Which version should I get? I am getting this error in my COMFYUI
I did clone the latest version

**Comment by omarei-omoto** [comment]
same issue after latest update, there are v5 nodes but all are red here

**Comment by MaraScott** [comment]
Hi,

sorry for delay, I don't receive the issues notifications for some reason.

the technical names of nodes have been renamed

`McBoaty_TilePrompter_v4` > `MaraScottMcBoatyTilePrompter_v4`
`McBoaty_Upscaler_v4` > `MaraScottMcBoatyUpscaler_v4`
`McBoaty_Refiner_v4` > `MaraScottMcBoatyRefiner_v4`

I will check the workflow graphs from this repo and update then accordingly, sorry for the issue

**Comment by Romanio1997** [comment]
When loading the graph, the following node types were not found

MaraScottMcBoatyRefiner_v5
MaraScottMcBoatyUpscaler_v5
MaraScottMcBoatyTilePrompter_v5
