### ISSUE TITLE
Feature Request : McBoaty - Change VLM & LLM parameters to use local LLM found in ...ComfyUI\models\LLM

### ISSUE THREAD

**Issue by Creare-d-arte** [MaraScott/ComfyUI_MaraScott_Nodes#146]
The Tile prompter currently links to Huggingface.

It would be better to give users the customizability options, and capability, of local VLM & LLM models.

**Comment by MaraScott** [comment]
you are right, I'm actualy thinking over the way McBoaty Works to make it more modular/flexible/efficient.

**Comment by MaraScott** [comment]
Implemented ollama node in the McBoaty Configurator node in v6
