### ISSUE TITLE
can't use aligen your stesp schedule for flux

### ISSUE THREAD

**Issue by davidchenhs** [MaraScott/ComfyUI_MaraScott_Nodes#148]
![image](https://github.com/user-attachments/assets/988eb46f-5264-45a5-ace2-01c2b8a9a07b)
how to use it with flux model ?

**Comment by MaraScott** [comment]
please share your workflow which trigger this error and all relative urls (checkpoints, loras, controlnet etc...) in order to run it on my computer and check the issue.

thx

**Comment by MaraScott** [comment]
as well, it seems that AYS is not good with FLUX

A good friend of mine said to me : 

> my understanding is that AYS is like optimized Karras scheduler implementation
> but Karras produces junk results with Flux. Beta seems best.
> so I don't see any bugs in log but the output is craptacular when using AYS

**Comment by MaraScott** [comment]
I think I finally found out what you meant, please update the node and try again

I have been able to execute AYS with this settings

![image](https://github.com/user-attachments/assets/2ce34240-5858-42d9-9559-2feefa0259a8)

**Comment by davidchenhs** [comment]
Thank you very much for your reply. This is already available. Your node is very useful. It is much better than the SD upscaler, but many people don’t know it.

**Comment by MaraScott** [comment]
Hi, thanks, happy to read that.
Please spread the word to help the node grow.

**Comment by davidchenhs** [comment]
The maximum number of tiles seems to be limited to 64. Can this limit be lifted?

**Comment by MaraScott** [comment]
Hi, I could increase it but that s a lot of tiles, why do you need more?

**Comment by davidchenhs** [comment]
Because I need to output a larger size and have higher detail requirements,
With the current setting, when I want to increase the upscale size, I have to increase the tile size,
But you know, with the same denoise factor, the details of larger blocks are not as detailed as those of smaller blocks.
So I want to test upscaling using smaller sized tiles, this node limit does not allow tiles to exceed 64

**Comment by davidchenhs** [comment]
And under this setting, as the input image size is different, we need to frequently adjust the size of the blocks,
 which will cause some trouble for some people who do not understand the principle.
For example, according to the block size of 512, the maximum resolution I can output is 4096. If it exceeds this resolution, I have to modify the block size.

**Comment by MaraScott** [comment]
Thanks for taking the time to answer.
which max size are you after ?

I've raised the max qty up to 16384x16384 which allow printing up to 4.33 x 4.33 meters

that should be enough :)

enjoy and please send me some example of High level details with some explanation on why do you want to achieve such details.

**Comment by davidchenhs** [comment]
https://github.com/user-attachments/assets/e69d602c-8a3f-492d-9500-8bd3cc19d2d8

I'm doing some testing and need to get these textures out and be able to do it more finely, and if the tiles size are larger, I'll get worse results,
The results we can get now are relatively much better.
By the way, this vae tiles seems to limit the minimum size to 320, 
I want to try to adjust to a smaller size of tiles, such as 256, 
but going below this limit causes me to be unable to output the image
Sincerely thank you again for your hard work

**Comment by MaraScott** [comment]
256 it is

**Comment by MaraScott** [comment]
please create new issue for new issue
