### ISSUE TITLE
Import failed

### ISSUE THREAD

**Issue by mofoni** [MaraScott/ComfyUI_MaraScott_Nodes#149]
Hi, i seem to have a problem loading your custom nodes.

below are the sections from the comand line i believe are relevant to this issue.

**System Info:**

`Python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]`

```
Total VRAM 24564 MB, total RAM 64655 MB
pytorch version: 2.4.1+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
Using pytorch cross attention
```
```
### Loading: ComfyUI-Manager (V2.51.2)
### ComfyUI Revision: 2730 [d72e871c] | Released on '2024-09-26'
```

*ComfyUI, all custom nodes and pytorch have been updated directly before writing this bugreport*

**actual Error:**

```
Traceback (most recent call last):
  File "G:\ComfyUI Installation\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1998, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "G:\ComfyUI Installation\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_MaraScott_Nodes\__init__.py", line 31, in <module>
    from .py.inc.lib.llm import MS_Llm
  File "G:\ComfyUI Installation\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_MaraScott_Nodes\py\inc\lib\llm.py", line 8, in <module>
    from groq import Groq
  File "G:\ComfyUI Installation\ComfyUI_windows_portable\python_embeded\Lib\site-packages\groq\__init__.py", line 3, in <module>
    from . import types
  File "G:\ComfyUI Installation\ComfyUI_windows_portable\python_embeded\Lib\site-packages\groq\types\__init__.py", line 5, in <module>
    from .model import Model as Model
  File "G:\ComfyUI Installation\ComfyUI_windows_portable\python_embeded\Lib\site-packages\groq\types\model.py", line 5, in <module>
    from .._models import BaseModel
  File "G:\ComfyUI Installation\ComfyUI_windows_portable\python_embeded\Lib\site-packages\groq\_models.py", line 25, in <module>
    from ._types import (
  File "G:\ComfyUI Installation\ComfyUI_windows_portable\python_embeded\Lib\site-packages\groq\_types.py", line 23, in <module>
    from httpx import URL, Proxy, Timeout, Response, BaseTransport, AsyncBaseTransport
ImportError: cannot import name 'BaseTransport' from 'httpx' (G:\ComfyUI Installation\ComfyUI_windows_portable\python_embeded\Lib\site-packages\httpx\__init__.py)

Cannot import G:\ComfyUI Installation\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_MaraScott_Nodes module for custom nodes: cannot import name 'BaseTransport' from 'httpx' (G:\ComfyUI Installation\ComfyUI_windows_portable\python_embeded\Lib\site-packages\httpx\__init__.py)
```

**Installed Custom Nodes:** 
_maybe someone knows of a compatibility issue, the Error might be the result of another nodepack, but i cant tell from the logmessage above...._
```
ComfyUI_SUNoise
ComfyUI_Noise
ComfyUi_NNLatentUpscale
comfyui_lora_tag_loader
cg-use-everywhere
sd-dynamic-thresholding
comfyui-previewlatent
cg-image-picker
ComfyUI-Latent-Modifiers
ComfyUI_SimpleTiles
ComfyUI-Lora-Auto-Trigger-Words
ComfyUI_yanc
wlsh_nodes
ComfyUI-AutomaticCFG
ComfyUI-Image-Saver
ComfyUI_Dave_CustomNode
ComfyUI_IPAdapter_plus
ComfyUI-TiledDiffusion
ComfyUI-Dev-Utils
execution-inversion-demo-comfyui
ComfyUI_UltimateSDUpscale
ComfyUI-Custom-Scripts
Derfuu_ComfyUI_ModdedNodes
ComfyUI-GGUF
ComfyUI-Advanced-ControlNet
ComfyUI-Translator
ComfyUI-JDCN
efficiency-nodes-comfyui
ComfyUI_bitsandbytes_NF4
ComfyUI_essentials
ComfyUI_Comfyroll_CustomNodes
comfyui_controlnet_aux
ComfyUI_Searge_LLM
ComfyUI-Inspire-Pack
rgthree-comfy
ComfyUI-KJNodes
ComfyUI-Manager
ComfyUI-JNodes
comfyui-dynamicprompts
ComfyUI-Impact-Pack
ComfyUI-Marigold
sdxl_prompt_styler-main
ComfyUI-Florence2
ComfyUI-Crystools
ComfyUI-SUPIR
comfy_mtb
ComfyUI-Inspyrenet-Rembg
was-node-suite-comfyui
```

**Comment by MaraScott** [comment]
Hi, could you let me know which version of httpx do you have ?

`python -m pip show httpx` ?

**Comment by mofoni** [comment]
of course: 

Version: 0.27.0

**Comment by MaraScott** [comment]
Could you remove all your nodes except comfyUI-manager and mine and restart ComfyUI, to see if the issue persist or not ?

**Comment by MaraScott** [comment]
can you use conda over python_embeded ?
logs always help

**Comment by MaraScott** [comment]
the issue is linked to grok

**Comment by MaraScott** [comment]
can you tell me the groq version installed and the python version you are using ?

**Comment by mofoni** [comment]
> can you use conda over python_embeded ?

sorry, i dont know how to used it. from what i could find it requires me to reinstall ComfyUI with Conda, right? (i know nothing about coding).
If you really want logs with conda from me, you would have to explain it to me or link a resource with an explanation. i couldnt find something with my available time.

>can you tell me the groq version installed and the python version 

the embedded python ComfyUI is using is 
`Python 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)] on win32`

i also got a list of all installed (embeded) python packages for you if it helps, _grok isnt among them_:

`['absl-py==2.1.0', 'accelerate==0.33.0', 'addict==2.4.0', 'aiofiles==24.1.0', 'aiohappyeyeballs==2.4.0', 'aiohttp-sse==2.2.0', 'aiohttp==3.10.6', 'aiosignal==1.3.1', 'albucore==0.0.14', 'albumentations==1.4.14', 'annotated-types==0.7.0', 'antlr4-python3-runtime==4.9.3', 'anyio==4.4.0', 'arrow==1.3.0', 'attrs==23.2.0', 'autocommand==2.2.2', 'backports.tarfile==1.2.0', 'beautifulsoup4==4.12.3', 'binaryornot==0.4.4', 'bitsandbytes==0.43.3', 'blend-modes==2.1.0', 'boto3==1.34.86', 'botocore==1.34.162', 'cachetools==5.5.0', 'certifi==2024.7.4', 'cffi==1.16.0', 'chardet==3.0.4', 'charset-normalizer==3.3.2', 'click==8.1.7', 'clip-interrogator==0.6.0', 'cmake==3.30.2', 'color-matcher==0.5.0', 'colorama==0.4.6', 'coloredlogs==15.0.1', 'colorlog==6.8.2', 'colour-science==0.4.4', 'contourpy==1.3.0', 'cookiecutter==2.6.0', 'cryptography==43.0.0', 'cssselect2==0.7.0', 'cstr==0.1.0', 'cycler==0.12.1', 'dataclasses-json==0.6.7', 'ddt==1.7.2', 'deep-translator==1.11.4', 'deepdiff==8.0.1', 'deepl==1.19.1', 'deprecated==1.2.14', 'diffusers==0.30.1', 'dill==0.3.8', 'diskcache==5.6.3', 'distro==1.9.0', 'docutils==0.21.2', 'dynamicprompts==0.30.2', 'easydict==1.13', 'einops==0.8.0', 'eval-type-backport==0.2.0', 'fairscale==0.4.13', 'fal-client==0.4.1', 'fastapi==0.112.2', 'ffmpy==0.3.0', 'filelock==3.15.4', 'flatbuffers==24.3.25', 'flet-core==0.23.2', 'flet-runtime==0.23.2', 'flet==0.23.2', 'fonttools==4.53.1', 'frozenlist==1.4.1', 'fsspec==2024.6.1', 'ftfy==6.2.3', 'fvcore==0.1.5.post20221221', 'gdown==5.2.0', 'gguf==0.10.0', 'gitdb==4.0.11', 'gitignore-parser==0.1.11', 'gitpython==3.1.43', 'googletrans==3.0.0', 'gpytoolbox==0.3.2', 'groq==0.10.0', 'h11==0.9.0', 'h2==3.2.0', 'hatchling==1.25.0', 'hpack==3.0.0', 'hstspreload==2024.9.1', 'httpcore==0.9.1', 'httptools==0.6.1', 'httpx-sse==0.4.0', 'httpx==0.13.3', 'huggingface-hub==0.24.2', 'humanfriendly==10.0', 'hyperframe==5.2.0', 'idna==2.10', 'imageio-ffmpeg==0.5.1', 'imageio==2.35.1', 'img2texture==1.0.6', 'importlib-metadata==8.4.0', 'importlib-resources==6.4.0', 'inflect==7.3.1', 'intel-openmp==2021.4.0', 'iopath==0.1.10', 'jaraco.context==5.3.0', 'jaraco.functools==4.0.1', 'jaraco.text==3.12.1', 'jax==0.4.31', 'jaxlib==0.4.31', 'jaxtyping==0.2.34', 'jinja2==3.1.4', 'jiter==0.5.0', 'jmespath==1.0.1', 'joblib==1.4.2', 'json-repair==0.28.4', 'jsonschema-specifications==2023.12.1', 'jsonschema==4.23.0', 'kiwisolver==1.4.5', 'kornia-rs==0.1.5', 'kornia==0.7.3', 'langdetect==1.0.9', 'lark-parser==0.12.0', 'lazy-loader==0.4', 'lightning-utilities==0.11.6', 'llama-cpp-python-cuda==0.2.89+cu121', 'llama-cpp-python==0.2.89+cpuavx2', 'llvmlite==0.43.0', 'lxml==5.3.0', 'manifold3d==2.5.1', 'mapbox-earcut==1.0.2', 'markdown-it-py==3.0.0', 'markupsafe==2.1.5', 'marshmallow==3.22.0', 'matplotlib==3.8.0', 'matrix-client==0.4.0', 'mdurl==0.1.2', 'mediapipe==0.10.14', 'mkl==2021.4.0', 'ml-dtypes==0.4.0', 'more-itertools==10.3.0', 'mpmath==1.3.0', 'mss==9.0.1', 'msvc-runtime==14.40.33807', 'multidict==6.0.5', 'mypy-extensions==1.0.0', 'nerfacc==0.5.3', 'networkx==3.3', 'ninja==1.11.1.1', 'numba==0.60.0', 'numpy==1.26.4', 'oauthlib==3.2.2', 'omegaconf==2.3.0', 'onnxruntime-gpu==1.19.0', 'onnxruntime==1.19.0', 'open-clip-torch==2.26.1', 'openai==1.43.0', 'opencv-contrib-python==4.10.0.84', 'opencv-python-headless==4.7.0.72', 'opencv-python==4.10.0.84', 'opt-einsum==3.3.0', 'orderly-set==5.2.2', 'packaging==23.2', 'pandas==2.2.2', 'pathspec==0.12.1', 'peft==0.12.0', 'piexif==1.1.3', 'pilgram==1.2.1', 'pillow==10.4.0', 'pip==24.2', 'pixeloe==0.0.10', 'platformdirs==4.2.2', 'pluggy==1.5.0', 'plyfile==1.1', 'pooch==1.8.2', 'portalocker==2.10.1', 'protobuf==4.25.4', 'psutil==6.0.0', 'py-cpuinfo==9.0.0', 'pycollada==0.8', 'pycparser==2.22', 'pydantic-core==2.20.1', 'pydantic==2.8.2', 'pygit2==1.15.1', 'pygithub==2.4.0', 'pygltflib==1.16.2', 'pygments==2.18.0', 'pyhocon==0.3.61', 'pyjwt==2.9.0', 'pymatting==1.1.12', 'pymcubes==0.1.6', 'pymeshlab==2023.12.post2', 'pynacl==1.5.0', 'pynvml==11.5.3', 'pyopenssl==24.2.1', 'pyparsing==3.1.4', 'pypng==0.20220715.0', 'pyreadline3==3.4.1', 'pysocks==1.7.1', 'python-dateutil==2.9.0.post0', 'python-dotenv==1.0.1', 'python-slugify==8.0.4', 'pytorch-lightning==2.4.0', 'pytorch-msssim==1.0.0', 'pytz==2024.1', 'pywin32==306', 'pyyaml==6.0.2', 'qrcode==7.4.2', 'redis==5.0.8', 'referencing==0.35.1', 'regex==2024.7.24', 'rembg==2.0.59', 'repath==0.9.0', 'reportlab==4.2.2', 'requests==2.32.3', 'requirements-parser==0.11.0', 'rfc3986==1.5.0', 'rich-argparse==1.5.2', 'rich==13.8.0', 'rpds-py==0.20.0', 'rtree==1.3.0', 's3transfer==0.10.2', 'safetensors==0.4.5', 'scikit-image==0.24.0', 'scikit-learn==1.5.1', 'scipy==1.14.1', 'seaborn==0.13.2', 'segment-anything==1.0', 'send2trash==1.8.3', 'sentencepiece==0.2.0', 'setuptools==73.0.1', 'shapely==2.0.6', 'shellingham==1.5.4', 'six==1.16.0', 'slangtorch==1.2.6', 'smmap==5.0.1', 'sniffio==1.3.1', 'sounddevice==0.5.0', 'soundfile==0.12.1', 'soupsieve==2.6', 'spandrel==0.4.0', 'starlette==0.38.2', 'surrealist==0.5.3', 'svg.path==6.3', 'svglib==1.5.1', 'sympy==1.13.1', 'tabulate==0.9.0', 'taming-transformers==0.0.1', 'tbb==2021.13.0', 'termcolor==2.4.0', 'text-unidecode==1.3', 'threadpoolctl==3.5.0', 'tifffile==2024.8.28', 'tiktoken==0.7.0', 'timm==1.0.9', 'tinycss2==1.3.0', 'tk==0.1.0', 'token-count==0.2.1', 'tokenizers==0.20.0', 'tomli==2.0.1', 'torch==2.4.1+cu121', 'torchaudio==2.4.1+cu121', 'torchmetrics==1.4.1', 'torchsde==0.2.6', 'torchtyping==0.1.5', 'torchvision==0.19.1+cu121', 'tqdm==4.66.5', 'trampoline==0.1.2', 'transformers==4.45.0', 'transparent-background==1.3.2', 'trimesh==4.4.8', 'trove-classifiers==2024.9.12', 'typeguard==2.13.3', 'typer==0.12.5', 'types-python-dateutil==2.9.0.20240821', 'types-setuptools==74.0.0.20240830', 'typing-extensions==4.12.2', 'typing-inspect==0.9.0', 'tzdata==2024.1', 'ultralytics-thop==2.0.5', 'ultralytics==8.2.84', 'urllib3==1.26.20', 'uvicorn==0.30.6', 'vhacdx==0.0.8.post1', 'watchdog==4.0.2', 'watchfiles==0.24.0', 'wcwidth==0.2.13', 'webencodings==0.5.1', 'websocket-client==1.8.0', 'websockets==13.0.1', 'wget==3.2', 'wheel==0.44.0', 'wrapt==1.16.0', 'xatlas==0.0.9', 'xxhash==3.5.0', 'yacs==0.1.8', 'yapf==0.40.2', 'yarl==1.12.1', 'zipp==3.20.1']`

**Comment by MaraScott** [comment]
Hi,

[conda](https://docs.anaconda.com/miniconda/) is a tool (miniconda for example) which allow you to isolate the packages in a specific environment 

In your case I'm pretty sure the error is due to some conflict between the python env from comfyui portable and your computer general pythin env

for instance you told me your httpx version is `0.27.0` using `python -m pip show httpx` but in the above list, your httpx package is `0.13.3` and grok requires at least `0.21.0`

I would suggest to follow that Guide to use conda which will save you a lots of time now and in the futur :
https://github.com/MaraScott/ComfyUI_MaraScott_Nodes/wiki/How-to-install-%60conda%60-to-isolate-the-python-package-from-your-computer

what do you think ?

**Comment by mofoni** [comment]
thanks - i will try to install this and clean up the mess i seem to have when i get the time.
