### ISSUE TITLE
No "For Loop" nodes to be found?

### ISSUE THREAD

**Issue by Jatts-Art** [MaraScott/ComfyUI_MaraScott_Nodes#153]
After installing the contents of this plugin, I noticed that the loop related nodes are no where to be found... not sure if this is intended or not intended or what?

**Comment by Jatts-Art** [comment]
So i attempted installing two ways, first I tried to install directly using git clone directly inside my "custom nodes" folder. it appeared it had installed properly, and it said it did, and i made sure to do the requirements list too... yet within comfyUI, i dont see any nodes at all.

Then i went to the releases page here on the github and downloaded that... suck that inside custom nodes folder, installed its requirements, and that did nothing either.

**Comment by Jatts-Art** [comment]
Okay yeah, pressing fix was able to repair things. But not sure why it isnt listed on there beforehand by default.

**Comment by MaraScott** [comment]
Weird, happy it works now
