### ISSUE TITLE
McBoaty : Can tile prompt add tile CFG value adjustment?

### ISSUE THREAD

**Issue by LAOGOU-666** [MaraScott/ComfyUI_MaraScott_Nodes#154]
Merely using prompt words cannot increase details, but increasing CFG values ​​can increase details. The block CFG function is strongly needed to control regional CFG. This is a great function.

**Comment by MaraScott** [comment]
Hi, sorry to get back to you so late.
this feature will be address in V6.

stay tuned

**Comment by MaraScott** [comment]
Hi, this has been added to v6 

![image](https://github.com/user-attachments/assets/b3802163-953b-4014-991c-a625e6062e08)

**Comment by LAOGOU-666** [comment]
> Hi, this has been added to v6
> 
> ![image](https://private-user-images.githubusercontent.com/482210/397449609-b3802163-953b-4014-991c-a625e6062e08.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY0NTQ2MDcsIm5iZiI6MTczNjQ1NDMwNywicGF0aCI6Ii80ODIyMTAvMzk3NDQ5NjA5LWIzODAyMTYzLTk1M2ItNDAxNC05OTFjLWE2MjVlNjA2MmUwOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwOVQyMDI1MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02N2I4NThlYWIyZWRjZTkwNTMzOGVmMzZmMzAzNWI3NzkzZGEyZWM2YWRiNDVjN2JkMWUwODY4NjM0N2Q5NmRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ogw-x5pSt7hE5vTSdxNKw4ienuvLi7e8ZwS5yfrpMAk)

Nice bro!
