### ISSUE TITLE
VAEDecode is failing

### ISSUE THREAD

**Issue by xulander** [MaraScott/ComfyUI_MaraScott_Nodes#163]
Error occurred when executing MaraScottMcBoatyUpscalerRefiner_v5:

VAEDecodeTiled.decode() takes 4 positional arguments but 5 were given

**Comment by xulander** [comment]
This is occurring in the large refiner node

**Comment by MaraScott** [comment]
Hi, 

Could you send me a screenshot of your about page in ComfyUI

I want to verify the version number you have

![image](https://github.com/user-attachments/assets/5a4a7b2a-ce29-455b-8a02-abd7477b679a)

**Comment by MaraScott** [comment]
I close the issue as you've updated the ComfyUI to latest and it worked
