### ISSUE TITLE
'No module named 'comfy_extras.nodes_align_your_steps'

### ISSUE THREAD

**Issue by laurentVeliscek** [MaraScott/ComfyUI_MaraScott_Nodes#53]
ComfyUI on mac,

I tried to install using comfyUI manager. but after installing, I get this error : 
Cannot import /Users/lalala/pinokio/api/comfyui.git/app/custom_nodes/ComfyUI_MaraScott_Nodes module for custom nodes: No module named 'comfy_extras.nodes_align_your_steps'

I googled this module with no success...

Any idea ?

Thanks

**Comment by ping3839** [comment]
+1

**Comment by MaraScott** [comment]
Hi,

did you upgrade your ComfyUI install ?
you should find it under /ComfyUI/comfy_extras 

![image](https://github.com/MaraScott/ComfyUI_MaraScott_Nodes/assets/482210/71bd70fc-3e92-4ac1-808e-a688c265e714)

**Comment by laurentVeliscek** [comment]
For mac users, It seems that adding this line in main.py (line 56, just after "import gc") :

`os.environ['PYTORCH_ENABLE_MPS_FALLBACK'] = "1"`

fixed the missing extra-nodes problem...

Hope it will help other users
