### ISSUE TITLE
McBoaty : Ignores output_size

### ISSUE THREAD

**Issue by GalaxyTimeMachine** [MaraScott/ComfyUI_MaraScott_Nodes#93]
Whether or not I have 1.0 or 2.0 in the output_size, McBoaty seems to just take the upscaler model default (4x) and output in that size.
![image](https://github.com/MaraScott/ComfyUI_MaraScott_Nodes/assets/52193044/b21b0dea-ab1c-4a6c-8cd5-cf95fee2b0a8)
![image](https://github.com/MaraScott/ComfyUI_MaraScott_Nodes/assets/52193044/476c6ead-9595-43ef-aa70-9fc8bac8314b)
![image](https://github.com/MaraScott/ComfyUI_MaraScott_Nodes/assets/52193044/c83c1e88-c0b1-4e54-ba94-81c511998c63)

**Comment by MaraScott** [comment]
Hi, thanks for that issue, it has been fixed, you need to update the node
